/**************************************************************************************
* Author: Seth Nida
* Course: EGR 226 - 905
* Date: 04/12/21
* Project: Lab 11
* File: Lab11-Part1+2.c
* Description: This program utilizes multiple instances of timer A to control a IR
* LED and a pin using timer A in input capture mode. Using these pins this program
* is responsable for generating and detecting a 10 Hz IR frequency and illuminating
* an on-board LED when detected and turning it off when the wave is not detected.
**************************************************************************************/
#include "msp.h"
#include "stdio.h"

volatile uint8_t detect10Hz,detect14Hz;
volatile uint16_t lastedge, currentedge, period;

void main(void)
{
    WDT_A->CTL = WDT_A_CTL_PW | WDT_A_CTL_HOLD;     // stop watchdog timer
    TimerA0Init();//function call to initialize PWM signal on P5.7
    SysTick_Init();//initializes the systick timer with interrupts

    P2->SEL0 &=~ BIT0;//sets up the led on P2.0
    P2->SEL1 &=~ BIT0;
    P2->DIR |= BIT0;//sets as output

    P2->SEL1&=~BIT5;//initializes pin connected to IR receiver
    P2->SEL0|=BIT5;
    P2->DIR&=~BIT5;

    TIMER_A0->CTL |= TIMER_A_CTL_TASSEL_2 | // Use SMCLK as clock source,
    TIMER_A_CTL_MC__UP | // Start timer in UP mode
    TIMER_A_CTL_ID_3 |// divide by 8 375KHz to capture 10 & 14 Hz
    TIMER_A_CTL_CLR; // clear TA0R

    TIMER_A0->CCTL[2] =TIMER_A_CCTLN_CM_1 | // Capture rising edge,
    TIMER_A_CCTLN_CCIS_0 | // Use CCI2A
    TIMER_A_CCTLN_CCIE | // Enable capture interrupt
    TIMER_A_CCTLN_CAP | // Enable capture mode,
    TIMER_A_CCTLN_SCS; // Synchronous capture

    NVIC->ISER[0] = 1 << ((TA0_N_IRQn) & 31); // Enable interrupt in NVIC vector
    __enable_irq ( );//enables global interrupts

    while(1){}//empty while loop to entertain the MSP432
}

/************************************************************************
* Function: TimerA0Init
* Inputs: None
* Outputs: None.
* Description: This function intializes timer A to generate a PWM signal to
* P5.7 of which powers the IR LED. The PWM signal has a duty cycle of
* fifty percent and a length of 10 Hz.
************************************************************************/
void TimerA0Init(void)
{
    P5->SEL0|=BIT7;//sets up P5.7 as in/out
    P5->SEL1&=~BIT7;
    P5->DIR|=BIT7;//sets P5.7 as output
    TIMER_A2->CCR[0]=300000;//initializes timer A period to 10 Hz
    TIMER_A2->CCTL[2]=0xE0;
    TIMER_A2->CTL=0x0214;
    TIMER_A2->CCR[2]=150000;//50% duty cycle
}

/************************************************************************
* Function: TA0_N_IRQHandler
* Inputs: None
* Outputs: None.
* Description: This function handles interrupts triggered by the voltage
* read on pin 2.5. if the voltage goes high this interrupt iterates. This
* interrupt is responsable for reseting the reload value of the systick timer
* and turning the red LED on.
************************************************************************/
void TA0_N_IRQHandler(void) // Timer A0 CCR2 interrupt service routine
{SysTick -> VAL = 1;//resets the counter on the systick timer
    P2->OUT|=BIT0;//turns on red LED
TIMER_A0->CCTL[2] &=~1; // Clear the TA.2 interrupt flag
TIMER_A0->CCTL[2] &= ~(TIMER_A_CCTLN_CCIFG); // Clear the interrupt flag
}

/************************************************************************
* Function: SysTick_Init
* Inputs: None
* Outputs: None.
* Description: This function initializes the systick timer to have reload
* value equal to 15 milliseconds and have interrupts that trigger on the reload
* of the timer.
************************************************************************/
void SysTick_Init (void) { //initialization of systic timer
SysTick -> CTRL = 0; // disable SysTick During set up
SysTick -> LOAD = 150000; // reload value for 1s interrupts
SysTick -> VAL = 0; // any write to current clears it
SysTick -> CTRL = 0x00000007; // enable systic, 3MHz, Interrupts
}

/************************************************************************
* Function: SysTick_Handler
* Inputs: None
* Outputs: None.
* Description: This function handles interrupts generated by the systick
* timer, within the interrupt hander an on-board LED is turned off if
* the interrupt is hit.
************************************************************************/
void SysTick_Handler (void) {
    P2->OUT&=~BIT0;//turns off red LED
}
