/**************************************************************************************
* Author: Seth Nida
* Course: EGR 226 - 905
* Date: 03/25/21
* Project: Lab 9
* File: Lab9-Part2.c
* Description: Part two of this lab activity required students to create a program that
* would display the numbers 0-9 on the seven segment LED cycling in one second intervals
* created by utilizing interrupts generated by the Systick timer.
**************************************************************************************/
#include "msp.h"

volatile int count=0;

void main(void)
{
	WDT_A->CTL = WDT_A_CTL_PW | WDT_A_CTL_HOLD;		// stop watchdog timer
	P4->SEL0&=~0xFF;
	P4->SEL0&=~0xFF;
	P4->DIR|=0xFF;//sets P4.0-P4.7 as output
	SysTick_Init();//function used to initialize the Systick timer
	__enable_irq();//enables global interrupts

	while(1){}//empty while loop to keep the MSP busy

}

/************************************************************************
* Function: SysTick_Init
* Inputs: None
* Outputs: None.
* Description: This function initializes the systick timer to have reload
* value equal to one second and have interrupts that trigger on the reload
* of the timer.
************************************************************************/
void SysTick_Init (void) { //initialization of systic timer
SysTick -> CTRL = 0; // disable SysTick During set up
SysTick -> LOAD = 3000000; // reload value for 1s interrupts
SysTick -> VAL = 0; // any write to current clears it
SysTick -> CTRL = 0x00000007; // enable systic, 3MHz, Interrupts
}

/************************************************************************
* Function: SysTick_Handler
* Inputs: None
* Outputs: None.
* Description: This function handles interrupts generated by the systick
* timer. Additonally this function serves the purpose of changing the number
* being displayed on the seven segment LED by changing which pins connected
* to it are set to HIGH.
************************************************************************/
void SysTick_Handler (void) {
    P4->OUT&=~0xFF;//ensures previous numbers are cleared from the LED
    if(count==0){P4->OUT|=0x3F;}//displays 0
    if(count==1){P4->OUT|=0x06;}//displays 1
    if(count==2){P4->OUT|=0x5B;}//displays 2
    if(count==3){P4->OUT|=0x4F;}//displays 3
    if(count==4){P4->OUT|=0x66;}//displays 4
    if(count==5){P4->OUT|=0x6D;}//displays 5
    if(count==6){P4->OUT|=0x7D;}//displays 6
    if(count==7){P4->OUT|=0x07;}//displays 7
    if(count==8){P4->OUT|=0x7F;}//displays 8
    if(count==9){P4->OUT|=0x67;}//displays 9

    count++;//increments the count
    if(count>9){count=0;}//ensures the count never surpasses 9
}
